CXXFLAGS_W = -Wunused-command-line-argument

common: date.o guest_profile.o reservation.o hotel.o
	g++ -o common date.o guest_profile.o reservation.o hotel.o

# date.o: date.cpp date.h
# 	g++ -c -o date.o date.cpp

# guest_profile.o: guest_profile.cpp guest_profile.h
# 	g++ -c -o guest_profile.o guest_profile.cpp

# reservation.o: reservation.cpp reservation.h
# 	g++ -c -o reservation.o reservation.cpp

# hotel.o: hotel.cpp hotel.h
# 	g++ -c -o hotel.o hotel.cpp

# clean:
# 	rm *.o


# common: date.o guest_profile.o
# 	g++ -o common date.o guest_profile.o


# date.o: date.cpp date.h
# 	g++ -c -o date.o date.cpp

# guest_profile.o: guest_profile.cpp guest_profile.h
# 	g++ -c -o guest_profile.o guest_profile.cpp


clean:
	rm *.o
